name: Node.js Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Set up environment variables
      run: |
        echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
        echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
        echo "ZH_TOKEN=${{ secrets.ZH_TOKEN }}" >> $GITHUB_ENV
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Set up environment variables
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
          echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
          echo "ZH_TOKEN=${{ secrets.ZH_TOKEN }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        run: npx semantic-release
